version: '3'

services:
  mariadb_1:
    image: mariadb:10.0.38
    hostname : mariadb_1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: secretary_db
      MYSQL_USER: normal_user
      MYSQL_PASSWORD: normal_password
    ports:
    - "8181:3306"
    volumes:
    - ./db:/docker-entrypoint-initdb.d

  mariadb_2:
    image: mariadb:10.0.38
    hostname : mariadb_2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: secretary_db
      MYSQL_USER: normal_user
      MYSQL_PASSWORD: normal_password
    ports:
    - "8182:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  secretary:
    container_name: secretary
    build:
      target : local
      context : .
    ports:
    - "8080:8080"
    - "8081:8081"
    - "5005:5005"
    volumes:
    - /var/log/secretary
    environment:
      DEBUG_OPTS_JAVA: -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/secretary_db?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/secretary_db?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: password
      SLEEP_TIME_IN_SEC: 10
    depends_on:
      - mariadb_1
      - mariadb_2

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    ports:
       - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.4.0
    hostname: broker
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  kafka-client:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka
    command: ["tail", "-f", "/dev/null"]
