server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  adminContextPath: /admin
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    io.appform.secretary: INFO
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

secretaryConfig:
  serviceBaseUrl: http://localhost:8080
  fileUploadPath: /secretary/v1/data/file/upload

shards:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      url: ${SHARD0_CONNECTION_STRING}
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        #hibernate.hbm2ddl.auto: create
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      logAbandonedConnections: true
      logValidationErrors: true
      checkConnectionWhileIdle: true
      checkConnectionOnConnect: true
      validationQueryTimeout: 1s
      removeAbandoned: true
      evictionInterval: 30s
      minIdleTime: 1m
    - driverClass: org.mariadb.jdbc.Driver
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      url: ${SHARD1_CONNECTION_STRING}
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        #hibernate.hbm2ddl.auto: create
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      logAbandonedConnections: true
      logValidationErrors: true
      checkConnectionWhileIdle: true
      checkConnectionOnConnect: true
      validationQueryTimeout: 1s
      removeAbandoned: true
      evictionInterval: 30s
      minIdleTime: 1m

swagger:
  resourcePackage: io.appform.secretary.server.resources
  title: Secretary
  description: Secretary Backend

rmqConfig:
  brokers:
    - host: ${RMQ_HOST}
      port: ${RMQ_PORT}
  userName: guest
  threadPoolSize: 32
  password: guest
  secure: false

actorConfigs:
  FILE_ROW_PROCESSOR:
    prefetchCount: 2
    concurrency: 2
    prefix: secretary.actor
    exchange: secretary.rows
    retryConfig:
      type: COUNT_LIMITED_EXPONENTIAL_BACKOFF
      maxAttempts: 6
      multipier: 100
      maxTimeBetweenRetries: 20s

statesmanHttpConfiguration:
  clientName: statesman
  host: 192.168.1.5
  port: 5050
  secure: false
  connections: 10
  idleTimeOutSeconds: 30
  connectTimeoutMs: 10000
  opTimeoutMs: 10000