version: '3.4'

services:
  mariadb_1:
    container_name: db_1
    image: mariadb:10.0.38
    hostname : mariadb_1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: secretary_db
      MYSQL_USER: normal_user
      MYSQL_PASSWORD: normal_password
    ports:
    - "8181:3306"
    volumes:
    - ./db:/docker-entrypoint-initdb.d

  mariadb_2:
    container_name: db_2
    image: mariadb:10.0.38
    hostname : mariadb_2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: secretary_db
      MYSQL_USER: normal_user
      MYSQL_PASSWORD: normal_password
    ports:
    - "8182:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  rmq:
    container_name: rmq
    image: rabbitmq:3.8-management
    hostname: rmq
    ports:
      - "5672:5672"
      - "15672:15672"

  secretary:
    container_name: secretary
    build:
      target : local
      context : .
    image: secretary:latest
    ports:
    - "8080:8080"
    - "8081:8081"
    - "5005:5005"
    volumes:
    - /var/log/secretary
    environment:
      DEBUG_OPTS_JAVA: -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
      SHARD0_CONNECTION_STRING: jdbc:mariadb://mariadb_1/secretary_db?createDatabaseIfNotExist=true
      SHARD1_CONNECTION_STRING: jdbc:mariadb://mariadb_2/secretary_db?createDatabaseIfNotExist=true
      RMQ_HOST: rmq
      RMQ_PORT: 5672
      DB_USER: root
      DB_PASSWORD: password
      SLEEP_TIME_IN_SEC: 10
    depends_on:
      - mariadb_1
      - mariadb_2
      - rmq
