name: Run Tests
on:
    push:
        branches-ignore:
            - 'master'
    pull_request:
        types: [opened, synchronize, reopened]
    release:
        types:
            - created
jobs:
    test_and_package:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - name: Checking out code base
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Testing and Packaging
              run: mvn -B verify -Dmaven.test.failure.ignore=false
              continue-on-error: false
              env:
                  GITHUB_ACTOR: ${{ github.actor }}
                  GITHUB_TOKEN: ${{ github.token }}